### ISSUE TITLE
 ValueError: '/data/data/org.test.myapp/files/app/libs/garden/garden.zbarcam' is not a package

### ISSUE THREAD

**Issue by wangyuncong123** [kivy-garden/garden.zbarcam#43]
garden.zbarcam is not a package.

my buildozer.spec:
# (list) Garden requirements
garden_requirements = xcamera,zbarcam

**Comment by AndreMiras** [comment]
Thank you for the bug report. Do you mind sharing more context of your trace.
This is runtime on device right? Or is it while building the apk?
Could you also share your source code?
To be honest I haven't tried putting it in the `garden_requirements` for a while as I pass it to `requirements` directly e.g. `https://github.com/kivy-garden/garden.zbarcam/archive/20190303.tar.gz`, see for instance https://github.com/AndreMiras/QrScan/blob/v20190303/buildozer.spec#L42

**Comment by wangyuncong123** [comment]
this is runtime on device.
my whole log is
06-02 19:51:18.230 12323 12353 I python  : Android kivy bootstrap done. __name__ is __main__
06-02 19:51:18.230 12323 12353 I python  : AND: Ran string
06-02 19:51:18.230 12323 12353 I python  : Run user program, change dir and execute entrypoint
06-02 19:51:18.974 12323 12353 I python  : [WARNING] [Config      ] Older configuration version detected (0 instead of 21)
06-02 19:51:18.974 12323 12353 I python  : [WARNING] [Config      ] Upgrading configuration in progress.
06-02 19:51:18.990 12323 12353 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/com.github.andremiras.zbarcamdemo/files/app/.kivy/logs/kivy_19-06-02_0.txt
06-02 19:51:18.991 12323 12353 I python  : [INFO   ] [Kivy        ] v1.11.0.dev0, git-Unknown, 20190602
06-02 19:51:18.992 12323 12353 I python  : [INFO   ] [Python      ] v3.7.1 (default, Jun  2 2019, 18:03:17) 
06-02 19:51:18.992 12323 12353 I python  : [Clang 6.0.2 (https://android.googlesource.com/toolchain/clang 183abd29fc496f55
06-02 19:51:21.305 12323 12353 I python  : [INFO   ] [Factory     ] 184 symbols loaded
06-02 19:51:22.504 12323 12353 I python  : [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
06-02 19:51:22.610 12323 12353 I python  :  Traceback (most recent call last):
06-02 19:51:22.611 12323 12353 I python  :    File "/home/wyc/.buildozer/android/app/main.py", line 5, in <module>
06-02 19:51:22.612 12323 12353 I python  :    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
06-02 19:51:22.614 12323 12353 I python  :    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
06-02 19:51:22.615 12323 12353 I python  :    File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
06-02 19:51:22.616 12323 12353 I python  :    File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
06-02 19:51:22.618 12323 12353 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/python-installs/zbarcamdemo/kivy/garden/__init__.py", line 100, in load_module
06-02 19:51:22.620 12323 12353 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/python-installs/zbarcamdemo/kivy/garden/__init__.py", line 104, in _load_module
06-02 19:51:22.621 12323 12353 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Lib/imp.py", line 244, in load_module
06-02 19:51:22.623 12323 12353 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Lib/imp.py", line 210, in load_package
06-02 19:51:22.624 12323 12353 I python  :  ValueError: '/data/data/com.github.andremiras.zbarcamdemo/files/app/libs/garden/garden.zbarcam' is not a package
06-02 19:51:22.624 12323 12353 I python  : Python for android ended.

my source code is :
main.py




from kivy.app import App
from kivy.garden.zbarcam import ZBarCam
from kivy.uix.widget import Widget

from kivy.lang import Builder



Builder.load_file('app.kv')




class TestApp(App):
    def __init__(self, **kwargs):
        super(TestApp, self).__init__(**kwargs)

    def build(self):
        return BoxLayout()

if __name__ == '__main__':
    TestApp().run()

app.kv
#:import ZBarCam kivy.garden.zbarcam.ZBarCam
#:import ZBarSymbol pyzbar.pyzbar.ZBarSymbol
BoxLayout:
    orientation: 'vertical'
    ZBarCam:
        id: zbarcam
        # optional, by default checks all types
        code_types: ZBarSymbol.QRCODE, ZBarSymbol.EAN13
    Label:
        size_hint: None, None
        size: self.texture_size[0], 50
        text: ', '.join([str(symbol.data) for symbol in zbarcam.symbols])


my buildozer.spec:
[app]

# (str) Title of your application
title = ZBarCam Demo

# (str) Package name
package.name = zbarcamdemo

# (str) Package domain (needed for android/ios packaging)
package.domain = com.github.andremiras

# (str) Source code where the main.py live
source.dir = /home/wyc

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
#version.regex = __version__ = ['"](.*)['"]
#version.filename = %(source.dir)s/version.py
# (list) Application requirements
# comma seperated e.g. requirements = sqlite3,kivy
requirements =
    android,
    kivy==5fc5385,
    libiconv,
    libzbar,
    Pillow==5.2.0,
    python3,
    pyzbar==0.1.8
# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy
# (list) Garden requirements
#garden_requirements =
garden_requirements = xcamera,zbarcam
# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png
# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png
# (str) Supported orientation (one of landscape, portrait or all)
orientation = portrait
# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY
#
# OSX Specific
#
#
# author = © Copyright Info
# change the major version of python used by the app
osx.python_version = 3
# Kivy version to use
osx.kivy_version = 1.9.1
#
# Android specific
#
# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0
# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF
# (list) Permissions
android.permissions = CAMERA
# (int) Target Android API, should be as high as possible.
android.api = 27
# (int) Minimum API your APK will support.
android.minapi = 21
# (int) Android SDK version to use
android.sdk = 20
# (str) Android NDK version to use
android.ndk = 17c
# (int) Android NDK API to use. This is the minimum API your app will support, it should usually match android.minapi.
android.ndk_api = 21
# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True
# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =
# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =
# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =
# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False
# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
android.accept_sdk_license = True
# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity
# (list) Pattern to whitelist for the whole project
#android.whitelist =
# (str) Path to a custom whitelist file
#android.whitelist_src =
# (str) Path to a custom blacklist file
#android.blacklist_src =
# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar
# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =
# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =
# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =
# (str) python-for-android branch to use, defaults to master
p4a.branch = master
# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME
# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png
# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =
# (list) Android additionnal libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so
# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False
# (list) Android application meta-data to set (key=value format)
#android.meta_data =
# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =
# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D
# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1
# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86
android.arch = armeabi-v7a
#
# Python for android (p4a) specific
#
# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =
# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =
# (str) Filename to the hook for p4a
#p4a.hook =
# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2
#
# iOS specific
#
# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"
# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s
[buildozer]
# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2
# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1
# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer
# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin
#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#
#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug

**Comment by AndreMiras** [comment]
Thanks for sharing. I'll try to reproduce (hopefully) this week and get back to you.

**Comment by GoBig87** [comment]
I'm seeing the same thing.  The issues has to deal with the __init__.py file.  There's no __init__.py file in the main directory only the zbarcam directory.  If you copy the __init__.py file outside of the zbarcam folder into the main folder (leave both) you can then import zbarcam.

**Comment by vmisiko** [comment]
guys i was able to compile an apk, but the runtime error i get is this, JavaException: JVM exception occurred: Fail to connect to camera service
[logcat.txt](https://github.com/kivy-garden/garden.zbarcam/files/3365870/logcat.txt)

**Comment by wangyuncong123** [comment]
i just copy all the zbarcam.py and zbarcam.kv into my source code and it solved.

**Comment by vmisiko** [comment]
@wangyuncong123 , i also used the example in the ReadMe.txt for zbarcam, it works fine in the destop, but when compiled it crashes on starting the app, and gives me the above runtime logcat.text. i don't where am going wrong

**Comment by wangyuncong123** [comment]
may not use  camera .      zbarcam.kv used xcamera.
07-07 19:01:56.116 5398 5434 I python : 27: id: camera
07-07 19:01:56.116 5398 5434 I python : **>> 28: resolution: 640, 480 # 1920, 1080**
07-07 19:01:56.117 5398 5434 I python : 29: allow_stretch: True
07-07 19:01:56.117 5398 5434 I python : 30:
07-07 19:01:56.118 5398 5434 I python : ...

**Comment by vmisiko** [comment]
Ok. But i already put xcamera in garden_requirements, or how again can i make it use xcamera instead of camera?

**Comment by wangyuncong123** [comment]
just use zbarcam.kv is done! 
let zbarcam.kv  with your main.py  together
#:import XCamera kivy.garden.xcamera.XCamera
<ZBarCam>:
    Widget:
        # invert width/height on rotated Android
        # https://stackoverflow.com/a/45192295/185510
        id: proxy
        XCamera:
            id: xcamera
            play: True
            resolution: root.resolution
            allow_stretch: True
            keep_ratio: True
            center: self.size and proxy.center
            size:
                (proxy.height, proxy.width) if root.is_android() \
                else (proxy.width, proxy.height)
            # Android camera rotation workaround, refs:
            # https://github.com/AndreMiras/garden.zbarcam/issues/3
            canvas.before:
                PushMatrix
                Rotate:
                    angle: -90 if root.is_android() else 0
                    origin: self.center
            canvas.after:
                PopMatrix
